name: netlify simple

on:
  pull_request:
  workflow_dispatch:

jobs:
  litedown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master
      - name: Dependencies
        run: ./run.sh install_all
      - name: install package and build site
        run: |
          R CMD build .
          R CMD INSTALL *.tar.gz
          R -e 'litedown::fuse_site("site")'
        shell: bash
      - name: netlify deploy
        uses: animint/animint-actions/netlify-simple@main
        with:
          netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
          path: site
