on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build docs

jobs:
  litedown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install package
        run: R CMD INSTALL .
      - name: Fuse site
        run: R -e 'litedown::fuse_site()'
      - name: netlify deploy
        uses: animint/animint-actions/netlify-deploy-comment@main
        with:
          netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
          pat_github_pr: ${{ secrets.PAT_GITHUB_PR }}
          path: site
          netlify_url: atime-docs.netlify.app
