name: update comment
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: |
          curl -L   -X PATCH   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"  -H "X-GitHub-Api-Version: 2026-03-10"  https://api.github.com/repos/tdhock/atime/issues/comments/4694905150
  -d '{"body":"Me too"}'
