name: update comment
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: update
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          ISSUES_API=https://api.github.com/repos/$GITHUB_REPOSITORY/issues
          CURL='curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2026-03-10"'
          PR_API=$ISSUES_API/$PR_NUMBER/comments
          FIRST_COMMENT_ID=$($CURL $PR_API?per_page=1 | grep '"id"' | head -1 | sed s/[^0-9]//g)
          if [ "$FIRST_COMMENT_ID" == "" ]; then CMD=$PR_API; else CMD=$ISSUES_API/comments/$FIRST_COMMENT_ID; fi; echo $CMD
          $CURL -X PATCH -H "Authorization: Bearer $TOKEN" $CMD -d '{"body":"This is the first comment again $CMD"}'
